# Generated by Django 4.1.5 on 2023-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('locationPin', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('userName', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('inOffice', models.CharField(blank=True, max_length=15, null=True)),
                ('inLunch', models.CharField(blank=True, max_length=15, null=True)),
                ('inBreak1', models.CharField(blank=True, max_length=15, null=True)),
                ('inBreak2', models.CharField(blank=True, max_length=15, null=True)),
                ('inBreak3', models.CharField(blank=True, max_length=15, null=True)),
                ('officeIn', models.CharField(blank=True, max_length=20, null=True)),
                ('officeOut', models.CharField(blank=True, max_length=20, null=True)),
                ('lunchIn', models.CharField(blank=True, max_length=20, null=True)),
                ('lunchOut', models.CharField(blank=True, max_length=20, null=True)),
                ('break1In', models.CharField(blank=True, max_length=20, null=True)),
                ('break1Out', models.CharField(blank=True, max_length=20, null=True)),
                ('break2In', models.CharField(blank=True, max_length=20, null=True)),
                ('break2Out', models.CharField(blank=True, max_length=20, null=True)),
                ('break3In', models.CharField(blank=True, max_length=20, null=True)),
                ('break3Out', models.CharField(blank=True, max_length=20, null=True)),
                ('didOffice', models.CharField(blank=True, max_length=15, null=True)),
                ('didLunch', models.CharField(blank=True, max_length=15, null=True)),
                ('didBreak1', models.CharField(blank=True, max_length=15, null=True)),
                ('didBreak2', models.CharField(blank=True, max_length=15, null=True)),
                ('didBreak3', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.CharField(blank=True, max_length=300, null=True)),
                ('meetForhr', models.CharField(blank=True, max_length=10, null=True)),
                ('meetForWeb', models.CharField(blank=True, max_length=10, null=True)),
                ('meetForSales', models.CharField(blank=True, max_length=10, null=True)),
                ('meetForAccFin', models.CharField(blank=True, max_length=10, null=True)),
                ('meetForBusiness', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='internCompelete',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('jobRole', models.CharField(blank=True, max_length=30, null=True)),
                ('titles', models.CharField(blank=True, max_length=10, null=True)),
                ('regRoll', models.CharField(blank=True, max_length=20, null=True)),
                ('rollNum', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('stDate', models.CharField(blank=True, max_length=20, null=True)),
                ('endDate', models.CharField(blank=True, max_length=20, null=True)),
                ('signBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=50, null=True)),
                ('stDate', models.CharField(blank=True, max_length=20, null=True)),
                ('endDate', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('approval', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
