# Generated by Django 4.1.5 on 2023-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_interncompelete_id_alter_payslip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
