# Generated by Django 4.1.5 on 2023-02-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_reqpayslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meetForAccFin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meetForBusiness',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meetForSales',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meetForWeb',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meetForhr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
