# Generated by Django 4.1.5 on 2023-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_event_meetforaccfin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='report',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
