# Generated by Django 4.1.5 on 2023-02-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='report',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
