# Generated by Django 4.1.5 on 2023-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employeeId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('crtDate', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('accessGroup', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('aadharNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('jobRole', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('empDate', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
                ('empType', models.CharField(blank=True, max_length=20, null=True)),
                ('totalHours', models.CharField(blank=True, max_length=20, null=True)),
                ('signBy', models.CharField(blank=True, max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
